### ISSUE TITLE
invalid version string in composer.json

### ISSUE THREAD

**Issue by Gamesh** [yegor256/phprack#103]
when i run: composer update

[UnexpectedValueException]
Invalid version string "2.0-SNAPSHOT"

maybe it should be 2.0-beta or something

usering Composer version 1.0-dev (833ce984264204e7d6576ab082660105c7d8f04c) 2015-02-17 21:55:44

**Comment by yegor256** [comment]
I fixed that and set to `2.0-beta`, thanks for suggesting.
