### ISSUE TITLE
composer cannot find v1.1 phprack distribution

### ISSUE THREAD

**Issue by Gamesh** [yegor256/phprack#105]
maybe there is something wrong here, though repository's maintainer in your coposer.json is yegor256/phprack, in pakagist its tpc2/phprack but it points to this repository, and when you run 
composer require "tpc2/phprack" "1.1" i get:

```
Installing tpc2/phprack (1.1)
    Downloading

    Failed to download tpc2/phprack from dist: The "https://api.github.com/repos/tpc2/phprack/zipball/36938a87e9bf2694d42e6374c623ec52dce79bc1" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing tpc2/phprack (1.1)
    Cloning 36938a87e9bf2694d42e6374c623ec52dce79bc1
```

**Comment by yegor256** [comment]
the correct location is `yegor256/phprack`. where do you think I should fix this?

**Comment by Gamesh** [comment]
i think it should be fixed in packagist, as from there composer gets its download location

**Comment by Gamesh** [comment]
unless @yegor256 it's not your package and somebody else has registered it in packagist under tpc2, then you just neet to register it in packagist

**Comment by yegor256** [comment]
it's mine. I just don't remember how I registered it there. I will check now...

**Comment by yegor256** [comment]
@Gamesh it's there now: https://packagist.org/packages/yegor256/phprack

**Comment by Gamesh** [comment]
maybe you should change the canonical url in the privious tpc2 package or mark it as discontinued and propose to use the new yegor256/phprack

**Comment by Gamesh** [comment]
by the way @yegor256 the new packagist yegor256/phprack work great in composer, no more 404 not found

**Comment by yegor256** [comment]
@Gamesh I marked the old package as "abandoned": https://packagist.org/packages/tpc2/phprack

It seems that problem is solved? Please close the issue
